# sudo: false
language: scala
scala:
- 2.11.4
- 2.10.4
jdk:
- oraclejdk7
- oraclejdk8
- openjdk6
- openjdk7
# cache:
#   directories:
#   - "$HOME/.sbt"
#   - "$HOME/.ivy2"
env:
# test across multiple versions of Neo4j:
- NEO4J_VERSION="2.1.6"
- NEO4J_VERSION="2.0.4"
- NEO4J_VERSION="1.9.9"
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test
- sbt ++$TRAVIS_SCALA_VERSION db:test
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coveralls
- test -n "${TRAVIS_TAG}" && test "${TRAVIS_JDK_VERSION}" = 'oraclejdk7' && test "${TRAVIS_SCALA_VERSION}"
  = "2.11.4" && sbt publishSigned sonatypeRelease
env:
  global:
  - secure: NoM0IHXcd8yXIGKeQmHFe902ATGKhIRDW5Uln0CB3SjXjygg7t9ysXlL0rz14oXpxVE0jhPrdIlnbtvuVEoupbermx2zQIdweh/om09pqH1xv33tVawPreExIOJ02SZkZ7sos+W5Q1gFsE3HvSdrZuoR3f2nXWV9Z0kQHmuNdIc=
  - secure: SExhNxk6rHNDbzRzKLzfWdEY99Ica2XoGR+th/t3XvqsgvtgCVsPA+ts1ZqGEKxiLqHRj/sBSbUAMVn5APFZad+zPrqJ+VGPuTLiC6v+4TYd0QbqikDNUp8BIBnUXcWkenBOw2GEnd/sAapglfM1cXhPuGte+8XVaI+6W7+0tUE=
before_install:
- openssl aes-256-cbc -k "$file_encryption_password" -in credentials.sbt.enc -out
  local.credentials.sbt -d
- openssl aes-256-cbc -k "$file_encryption_password" -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -k "$file_encryption_password" -in pubring.gpg.enc -out local.pubring.gpg
  -d
# install Neo4j locally:
- wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
- tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
- neo4j-community-$NEO4J_VERSION/bin/neo4j start
