sudo: false
language: scala
scala:
- 2.11.4
- 2.10.4
jdk:
- oraclejdk7
- oraclejdk8
- openjdk6
- openjdk7
cache:
  directories:
  - $HOME/.sbt/boot
  - $HOME/.ivy2
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coveralls
env:
  global:
    secure: HvsNr1JOG8un5ehN9Clw6YEb4SRjHb5xLwx9+TZ2K3DyOmalRpyIXXYre16t1t4X3m2fuP2EdiYIGsFOv3oY8L0NnnIUw0OMs4uO1vYUPB9NQ8Ohd5KCs3R+OFa30xNSBds6Oqk0DQ6Jr1J86PZINbkKaFcKTjuQuWhfUqxKf7c=
