sudo: false
language: scala
cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
  - "$HOME/neo4j"
scala:
- 2.11.8
- 2.10.5
jdk:
- oraclejdk7
- oraclejdk8
# - openjdk6 # httpmocks do not work with java6
# - openjdk7
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test
- sbt ++$TRAVIS_SCALA_VERSION test-integration:test # integration tests need a running neo4j instance
- rm ~/.sbt/boot/scala-*/org.scala-sbt/sbt/*/sbt.components.lock ~/.sbt/boot/sbt.boot.lock
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coveralls
# fix jdk and neo4j version but release for each scala version separately
- test -n "${TRAVIS_TAG}" && test "${TRAVIS_JDK_VERSION}" = 'oraclejdk7' && test "${NEO4J_VERSION}" = '2.2.1' && sbt ++$TRAVIS_SCALA_VERSION publishSigned sonatypeRelease # take an arbitrary fixed combination from build matrix for each scala version and publish
env:
  matrix:
    # test across multiple versions of Neo4j:
    - NEO4J_VERSION="3.0.4"
    - NEO4J_VERSION="2.3.7"
    - NEO4J_VERSION="2.2.10"
    # - NEO4J_VERSION="2.1.7" # does not isolate transactions
    # - NEO4J_VERSION="2.0.4" # does not support property += {...}
  global:
    - secure: NoM0IHXcd8yXIGKeQmHFe902ATGKhIRDW5Uln0CB3SjXjygg7t9ysXlL0rz14oXpxVE0jhPrdIlnbtvuVEoupbermx2zQIdweh/om09pqH1xv33tVawPreExIOJ02SZkZ7sos+W5Q1gFsE3HvSdrZuoR3f2nXWV9Z0kQHmuNdIc=
    - secure: SExhNxk6rHNDbzRzKLzfWdEY99Ica2XoGR+th/t3XvqsgvtgCVsPA+ts1ZqGEKxiLqHRj/sBSbUAMVn5APFZad+zPrqJ+VGPuTLiC6v+4TYd0QbqikDNUp8BIBnUXcWkenBOw2GEnd/sAapglfM1cXhPuGte+8XVaI+6W7+0tUE=
before_install:
- JAVA_HOME=$(jdk_switcher home oraclejdk8) ./travis_setup_neo4j.sh
- openssl aes-256-cbc -k "$file_encryption_password" -in credentials.sbt.enc -out
  local.credentials.sbt -d
- openssl aes-256-cbc -k "$file_encryption_password" -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -k "$file_encryption_password" -in pubring.gpg.enc -out local.pubring.gpg
  -d
